### ISSUE TITLE
Ada hello world inside SGX enclave

### ISSUE THREAD

**Issue by senier** [Componolit/VetFS#4]
Use the Intel SGX SDK to create a bare-metal Ada application. It should use both, ECALLs and OCALLs (e.g. passing in an integer to the Ada program which adds a constant and outputs the result through a print function).

The way to go is to use GNAT when compiling the SGX SDK example, adding an Ada main an respective startup code (that, e.g. calls adamain). A minimal runtime is used to support that standalone application, similar to what we are doing in Genode's Ada runtime or how it's done in Muen.

**Comment by treiher** [comment]
We rely on the build system of the Intel SGX SDK to link an Ada stand-alone library into the enclave code. Usually Ada programs are linked against the GNAT library. With SGX this is not desirable, as this would require many libc functions which are not supported inside an enclave. Therefore, we created an almost empty RTS. This has the drawback that we cannot rely on packages provided by the GNAT library, which would be helpful to realize safe C bindings. The current Hello World program just maps Ada types to C types, which in practice are not always compatible (e.g., an Ada string is not terminated by a null character). Maybe we should think of moving some functionality like the Interface.C package back to the RTS. The problem here is that this would also require to enable Exceptions and probably further functionalities.

**Comment by senier** [comment]
A agree that we should add `Interfaces.C` to our runtime. Are you sure we need Exceptions then? If so, we have some options: (1) support exceptions in a limited form as @jklmnn did on Genode and prove they don't happen (2) create a version of `Interfaces.C` that does not required exceptions or (3) create a custom package for interfacing with C.

**Comment by treiher** [comment]
The implementation of `Interfaces.C` makes use of exceptions to signal errors during type conversion. How hard would it be to realize option (1)? Would it in general be possible to realize option (2) by adding preconditions to these functions, so that we safely can remove the usage of exceptions, as these error cases cannot occur anymore? But I guess that could be much harder than (1). I think modifying the function signatures for an alternative error reporting or creating a custom package should be the last resort.

**Comment by senier** [comment]
An Ada, an exceptions is raised if preconditions are false (at least you can enable that behavior during compilation). Then we are back at (1). I agree that (3) should be last resort.

I chatted with @jklmnn about the `Interfaces.C` issue, as we discovered that we need it in the context of our Genode/Ada binding. Option (1) should be doable with reasonable effort. Let's talk about that tomorrow.

**Comment by treiher** [comment]
A working Hello World can be found in [Componolit/sgx-ada](https://github.com/Componolit/sgx-ada).
